# EDA

In [2]:
import subprocess
import sys

# Asegurar la instalación de pandas
try:
    import pandas as pd
except ImportError:
    print("pandas is not installed. Installing...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "pandas", "--user"])
    import pandas as pd

# Asegurar la instalación de matplotlib
try:
    import matplotlib.pyplot as plt
except ImportError:
    print("matplotlib is not installed. Installing...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "matplotlib", "--user"])
    import matplotlib.pyplot as plt

# Asegurar la instalación de ydata-profiling
try:
    from ydata_profiling import ProfileReport
except ImportError:
    print("ydata-profiling is not installed. Installing...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "ydata-profiling", "--user"])
    from ydata_profiling import ProfileReport

In [3]:
dataset_path = 'c:/Users/48242450/Downloads/used_cars_data.csv'

df=pd.read_csv(dataset_path)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   S.No.              7253 non-null   int64  
 1   Name               7253 non-null   object 
 2   Location           7253 non-null   object 
 3   Year               7253 non-null   int64  
 4   Kilometers_Driven  7253 non-null   int64  
 5   Fuel_Type          7253 non-null   object 
 6   Transmission       7253 non-null   object 
 7   Owner_Type         7253 non-null   object 
 8   Mileage            7251 non-null   object 
 9   Engine             7207 non-null   object 
 10  Power              7207 non-null   object 
 11  Seats              7200 non-null   float64
 12  New_Price          1006 non-null   object 
 13  Price              6019 non-null   float64
dtypes: float64(2), int64(3), object(9)
memory usage: 793.4+ KB


In [20]:
df = df.drop('Mileage', axis=1)

In [21]:
df.head(3)

S.No.                              Name Location  Year  Kilometers_Driven  \
0      0            Maruti Wagon R LXI CNG   Mumbai  2010              72000   
1      1  Hyundai Creta 1.6 CRDi SX Option     Pune  2015              41000   
2      2                      Honda Jazz V  Chennai  2011              46000   

  Fuel_Type Transmission Owner_Type   Engine      Power  Seats  New_Price  \
0       CNG       Manual      First   998 CC  58.16 bhp    5.0        NaN   
1    Diesel       Manual      First  1582 CC  126.2 bhp    5.0        NaN   
2    Petrol       Manual      First  1199 CC   88.7 bhp    5.0  8.61 Lakh   

   Price  
0   1.75  
1  12.50  
2   4.50

In [22]:
df.columns

Index(['S.No.', 'Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Engine', 'Power', 'Seats', 'New_Price',
       'Price'],
      dtype='object')

In [4]:
df['Power'] = df['Power'].apply(lambda x: str(x)[:-3] if isinstance(x, str) and len(x) >= 3 else x)

In [5]:
df['Engine'] = df['Engine'].apply(lambda x: str(x)[:-2] if isinstance(x, str) and len(x) >= 2 else x)
df

S.No.                                               Name    Location  \
0         0                             Maruti Wagon R LXI CNG      Mumbai   
1         1                   Hyundai Creta 1.6 CRDi SX Option        Pune   
2         2                                       Honda Jazz V     Chennai   
3         3                                  Maruti Ertiga VDI     Chennai   
4         4                    Audi A4 New 2.0 TDI Multitronic  Coimbatore   
...     ...                                                ...         ...   
7248   7248                  Volkswagen Vento Diesel Trendline   Hyderabad   
7249   7249                             Volkswagen Polo GT TSI      Mumbai   
7250   7250                             Nissan Micra Diesel XV     Kolkata   
7251   7251                             Volkswagen Polo GT TSI        Pune   
7252   7252  Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...       Kochi   

      Year  Kilometers_Driven Fuel_Type Transmission Owner_Type     Mileage  \
0     2010              72000       CNG       Manual      First  26.6 km/kg   
1     2015              41000    Diesel       Manual      First  19.67 kmpl   
2     2011              46000    Petrol       Manual      First   18.2 kmpl   
3     2012              87000    Diesel       Manual      First  20.77 kmpl   
4     2013              40670    Diesel    Automatic     Second   15.2 kmpl   
...    ...                ...       ...          ...        ...         ...   
7248  2011              89411    Diesel       Manual      First  20.54 kmpl   
7249  2015              59000    Petrol    Automatic      First  17.21 kmpl   
7250  2012              28000    Diesel       Manual      First  23.08 kmpl   
7251  2013              52262    Petrol    Automatic      Third   17.2 kmpl   
7252  2014              72443    Diesel    Automatic      First   10.0 kmpl   

     Engine   Power  Seats  New_Price  Price  
0      998   58.16     5.0        NaN   1.75  
1     1582   126.2     5.0        NaN  12.50  
2     1199    88.7     5.0  8.61 Lakh   4.50  
3     1248   88.76     7.0        NaN   6.00  
4     1968   140.8     5.0        NaN  17.74  
...     ...     ...    ...        ...    ...  
7248  1598   103.6     5.0        NaN    NaN  
7249  1197   103.6     5.0        NaN    NaN  
7250  1461    63.1     5.0        NaN    NaN  
7251  1197   103.6     5.0        NaN    NaN  
7252  2148     170     5.0        NaN    NaN  

[7253 rows x 14 columns]

In [7]:
df['Mileage'] = df['Mileage'].str.replace(r'[^0-9.]', '', regex=True).astype(float)

# Ver los primeros valores de Mileage después de limpiar
print("\nValores de Mileage después de limpiar:")
print(df['Mileage'].head())

# Verificar si hay valores NaN después de la conversión
missing_mileage = df['Mileage'].isna().sum()
print(f"\nNúmero de valores faltantes en Mileage después de la limpieza: {missing_mileage}")


Valores de Mileage después de limpiar:
0    26.60
1    19.67
2    18.20
3    20.77
4    15.20
Name: Mileage, dtype: float64

Número de valores faltantes en Mileage después de la limpieza: 2


In [8]:
missing_values = df.isna().sum()

# Mostrar los valores faltantes por columna
print("Valores faltantes por columna:")
print(missing_values)

# Calcular el número total de valores faltantes en el DataFrame
total_missing = df.isna().sum().sum()
print(f"\nNúmero total de valores faltantes en el DataFrame: {total_missing}")

Valores faltantes por columna:
S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 46
Power                  46
Seats                  53
New_Price            6247
Price                1234
dtype: int64

Número total de valores faltantes en el DataFrame: 7628


In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, confusion_matrix

# Asumiendo que df ya está definido y contiene tus datos

# Manejo de valores faltantes en atributos numéricos
numeric_features = ['Year', 'Kilometers_Driven', 'Seats']
df[numeric_features] = df[numeric_features].fillna(df[numeric_features].mean())

# Convertir el atributo 'Mileage' a string antes de limpiar
df['Mileage'] = df['Mileage'].astype(str)

# Reemplazar cualquier cadena vacía con NaN
df['Mileage'] = df['Mileage'].replace('', np.nan)

# Limpiar el atributo Mileage para que solo tenga números
df['Mileage'] = df['Mileage'].str.replace(r'[^0-9.]', '', regex=True)

# Convertir 'Mileage' a float, forzando los errores a NaN
df['Mileage'] = pd.to_numeric(df['Mileage'], errors='coerce')

# Rellenar valores faltantes en 'Mileage' con la media
df['Mileage'] = df['Mileage'].fillna(df['Mileage'].mean())

# Convertir valores no numéricos de "New_Price" a NaN y eliminar filas donde "New_Price" es NaN
df['New_Price'] = df['New_Price'].astype(str).str.replace(r'[^0-9.]', '', regex=True)
df['New_Price'] = pd.to_numeric(df['New_Price'], errors='coerce')
df = df.dropna(subset=['New_Price'])

# Convertir "New_Price" en categorías (ejemplo: barato, medio, caro)
df['New_Price_Category'] = pd.qcut(df['New_Price'], q=3, labels=['barato', 'medio', 'caro'])

# Seleccionar solo las características numéricas para X
X = df[numeric_features + ['Mileage']]
y = df['New_Price_Category']

# Crear el preprocesador (escalado)
preprocessor = StandardScaler()

# Definir el modelo de regresión logística
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000))
])

# Dividir los datos en conjunto de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Entrenar el modelo
model.fit(X_train, y_train)

# Predecir las categorías para el conjunto de prueba
y_pred = model.predict(X_test)

# Evaluar el modelo
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f'Precisión del modelo: {accuracy:.2f}')
print('Matriz de confusión:')
print(conf_matrix)


Precisión del modelo: 0.54
Matriz de confusión:
[[36 14 24]
 [ 5 54  7]
 [19 24 19]]


C:\Users\48242450\AppData\Local\Temp\ipykernel_9588\643265845.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[numeric_features] = df[numeric_features].fillna(df[numeric_features].mean())
C:\Users\48242450\AppData\Local\Temp\ipykernel_9588\643265845.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Mileage'] = df['Mileage'].astype(str)
C:\Users\48242450\AppData\Local\Temp\ipykernel_9588\643265845.py:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.

Primera fila (Categoría "barato"):

36 instancias clasificadas correctamente como "barato".

14 instancias clasificadas erróneamente como "medio".

24 instancias clasificadas erróneamente como "caro".

Segunda fila (Categoría "medio"):

5 instancias clasificadas erróneamente como "barato".

54 instancias clasificadas correctamente como "medio".

7 instancias clasificadas erróneamente como "caro".

Tercera fila (Categoría "caro"):

19 instancias clasificadas erróneamente como "barato".

24 instancias clasificadas erróneamente como "medio".

19 instancias clasificadas correctamente como "caro".

In [20]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# Asumiendo que df ya está definido y contiene tus datos

# Manejo de valores faltantes en atributos numéricos
numeric_features = ['Year', 'Kilometers_Driven', 'Seats']
df[numeric_features] = df[numeric_features].fillna(df[numeric_features].mean())

# Manejo de valores faltantes y limpieza en atributos categóricos
categorical_features = ['Fuel_Type', 'Transmission', 'Owner_Type']

# Convertir el atributo 'Mileage' a string antes de limpiar
df['Mileage'] = df['Mileage'].astype(str)

# Reemplazar cualquier cadena vacía con NaN
df['Mileage'] = df['Mileage'].replace('', np.nan)

# Limpiar el atributo Mileage para que solo tenga números
df['Mileage'] = df['Mileage'].str.replace(r'[^0-9.]', '', regex=True)

# Convertir 'Mileage' a float, forzando los errores a NaN
df['Mileage'] = pd.to_numeric(df['Mileage'], errors='coerce')

# Rellenar valores faltantes en 'Mileage' con la media
df['Mileage'] = df['Mileage'].fillna(df['Mileage'].mean())

# Convertir valores no numéricos de "New_Price" a NaN y eliminar filas donde "New_Price" es NaN
df['New_Price'] = df['New_Price'].astype(str).str.replace(r'[^0-9.]', '', regex=True)
df['New_Price'] = pd.to_numeric(df['New_Price'], errors='coerce')
df = df.dropna(subset=['New_Price'])

# Convertir "New_Price" en categorías (ejemplo: barato, medio, caro)
df['New_Price_Category'] = pd.qcut(df['New_Price'], q=3, labels=['barato', 'medio', 'caro'])

# Separar características numéricas y categóricas
X_numeric = df[numeric_features + ['Mileage']]
X_categorical = df[categorical_features]
y = df['New_Price_Category']

# Crear el preprocesador para atributos numéricos y categóricos
numeric_transformer = StandardScaler()
categorical_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features + ['Mileage']),
        ('cat', categorical_transformer, categorical_features)
    ]
)

# Definir el modelo de regresión logística
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000))
])

# Dividir los datos en conjunto de entrenamiento y prueba
X = df[numeric_features + ['Mileage'] + categorical_features]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Entrenar el modelo
model.fit(X_train, y_train)

# Predecir las categorías para el conjunto de prueba
y_pred = model.predict(X_test)

# Evaluar el modelo
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f'Precisión del modelo: {accuracy:.2f}')
print('Matriz de confusión:')
print(conf_matrix)


Precisión del modelo: 0.75
Matriz de confusión:
[[58  5 11]
 [ 3 59  4]
 [20  8 34]]
